/* 
 * API Escape Game
 *
 * Service web pour gérer les informations de EGC
 *
 * OpenAPI spec version: beta 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IJoueurArchiveApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Removes the JoueurArchive resource.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns></returns>
        void DeleteJoueurArchiveItem (string id);

        /// <summary>
        /// Removes the JoueurArchive resource.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> DeleteJoueurArchiveItemWithHttpInfo (string id);
        /// <summary>
        /// Retrieves the collection of JoueurArchive resources.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">The collection page number (optional)</param>
        /// <returns>List&lt;JoueurArchive&gt;</returns>
        List<JoueurArchive> GetJoueurArchiveCollection (int? page = null);

        /// <summary>
        /// Retrieves the collection of JoueurArchive resources.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">The collection page number (optional)</param>
        /// <returns>ApiResponse of List&lt;JoueurArchive&gt;</returns>
        ApiResponse<List<JoueurArchive>> GetJoueurArchiveCollectionWithHttpInfo (int? page = null);
        /// <summary>
        /// Retrieves a JoueurArchive resource.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>JoueurArchive</returns>
        JoueurArchive GetJoueurArchiveItem (string id);

        /// <summary>
        /// Retrieves a JoueurArchive resource.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of JoueurArchive</returns>
        ApiResponse<JoueurArchive> GetJoueurArchiveItemWithHttpInfo (string id);
        /// <summary>
        /// Creates a JoueurArchive resource.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="joueurArchive">The new JoueurArchive resource (optional)</param>
        /// <returns>JoueurArchive</returns>
        JoueurArchive PostJoueurArchiveCollection (JoueurArchive joueurArchive = null);

        /// <summary>
        /// Creates a JoueurArchive resource.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="joueurArchive">The new JoueurArchive resource (optional)</param>
        /// <returns>ApiResponse of JoueurArchive</returns>
        ApiResponse<JoueurArchive> PostJoueurArchiveCollectionWithHttpInfo (JoueurArchive joueurArchive = null);
        /// <summary>
        /// Replaces the JoueurArchive resource.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="joueurArchive">The updated JoueurArchive resource (optional)</param>
        /// <returns>JoueurArchive</returns>
        JoueurArchive PutJoueurArchiveItem (string id, JoueurArchive joueurArchive = null);

        /// <summary>
        /// Replaces the JoueurArchive resource.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="joueurArchive">The updated JoueurArchive resource (optional)</param>
        /// <returns>ApiResponse of JoueurArchive</returns>
        ApiResponse<JoueurArchive> PutJoueurArchiveItemWithHttpInfo (string id, JoueurArchive joueurArchive = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Removes the JoueurArchive resource.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task DeleteJoueurArchiveItemAsync (string id);

        /// <summary>
        /// Removes the JoueurArchive resource.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> DeleteJoueurArchiveItemAsyncWithHttpInfo (string id);
        /// <summary>
        /// Retrieves the collection of JoueurArchive resources.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">The collection page number (optional)</param>
        /// <returns>Task of List&lt;JoueurArchive&gt;</returns>
        System.Threading.Tasks.Task<List<JoueurArchive>> GetJoueurArchiveCollectionAsync (int? page = null);

        /// <summary>
        /// Retrieves the collection of JoueurArchive resources.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">The collection page number (optional)</param>
        /// <returns>Task of ApiResponse (List&lt;JoueurArchive&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<JoueurArchive>>> GetJoueurArchiveCollectionAsyncWithHttpInfo (int? page = null);
        /// <summary>
        /// Retrieves a JoueurArchive resource.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>Task of JoueurArchive</returns>
        System.Threading.Tasks.Task<JoueurArchive> GetJoueurArchiveItemAsync (string id);

        /// <summary>
        /// Retrieves a JoueurArchive resource.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>Task of ApiResponse (JoueurArchive)</returns>
        System.Threading.Tasks.Task<ApiResponse<JoueurArchive>> GetJoueurArchiveItemAsyncWithHttpInfo (string id);
        /// <summary>
        /// Creates a JoueurArchive resource.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="joueurArchive">The new JoueurArchive resource (optional)</param>
        /// <returns>Task of JoueurArchive</returns>
        System.Threading.Tasks.Task<JoueurArchive> PostJoueurArchiveCollectionAsync (JoueurArchive joueurArchive = null);

        /// <summary>
        /// Creates a JoueurArchive resource.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="joueurArchive">The new JoueurArchive resource (optional)</param>
        /// <returns>Task of ApiResponse (JoueurArchive)</returns>
        System.Threading.Tasks.Task<ApiResponse<JoueurArchive>> PostJoueurArchiveCollectionAsyncWithHttpInfo (JoueurArchive joueurArchive = null);
        /// <summary>
        /// Replaces the JoueurArchive resource.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="joueurArchive">The updated JoueurArchive resource (optional)</param>
        /// <returns>Task of JoueurArchive</returns>
        System.Threading.Tasks.Task<JoueurArchive> PutJoueurArchiveItemAsync (string id, JoueurArchive joueurArchive = null);

        /// <summary>
        /// Replaces the JoueurArchive resource.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="joueurArchive">The updated JoueurArchive resource (optional)</param>
        /// <returns>Task of ApiResponse (JoueurArchive)</returns>
        System.Threading.Tasks.Task<ApiResponse<JoueurArchive>> PutJoueurArchiveItemAsyncWithHttpInfo (string id, JoueurArchive joueurArchive = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class JoueurArchiveApi : IJoueurArchiveApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="JoueurArchiveApi"/> class.
        /// </summary>
        /// <returns></returns>
        public JoueurArchiveApi(String basePath)
        {
            this.Configuration = new Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="JoueurArchiveApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public JoueurArchiveApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Removes the JoueurArchive resource. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns></returns>
        public void DeleteJoueurArchiveItem (string id)
        {
             DeleteJoueurArchiveItemWithHttpInfo(id);
        }

        /// <summary>
        /// Removes the JoueurArchive resource. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> DeleteJoueurArchiveItemWithHttpInfo (string id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling JoueurArchiveApi->DeleteJoueurArchiveItem");

            var localVarPath = "/joueur_archives/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", Configuration.ApiClient.ParameterToString(id)); // path parameter

            // authentication (basicAuth) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(Configuration.Username) || !String.IsNullOrEmpty(Configuration.Password))
            {
                localVarHeaderParams["Authorization"] = "Basic " + ApiClient.Base64Encode(Configuration.Username + ":" + Configuration.Password);
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteJoueurArchiveItem", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// Removes the JoueurArchive resource. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task DeleteJoueurArchiveItemAsync (string id)
        {
             await DeleteJoueurArchiveItemAsyncWithHttpInfo(id);

        }

        /// <summary>
        /// Removes the JoueurArchive resource. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> DeleteJoueurArchiveItemAsyncWithHttpInfo (string id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling JoueurArchiveApi->DeleteJoueurArchiveItem");

            var localVarPath = "/joueur_archives/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", Configuration.ApiClient.ParameterToString(id)); // path parameter

            // authentication (basicAuth) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(Configuration.Username) || !String.IsNullOrEmpty(Configuration.Password))
            {
                localVarHeaderParams["Authorization"] = "Basic " + ApiClient.Base64Encode(Configuration.Username + ":" + Configuration.Password);
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteJoueurArchiveItem", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// Retrieves the collection of JoueurArchive resources. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">The collection page number (optional)</param>
        /// <returns>List&lt;JoueurArchive&gt;</returns>
        public List<JoueurArchive> GetJoueurArchiveCollection (int? page = null)
        {
             ApiResponse<List<JoueurArchive>> localVarResponse = GetJoueurArchiveCollectionWithHttpInfo(page);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieves the collection of JoueurArchive resources. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">The collection page number (optional)</param>
        /// <returns>ApiResponse of List&lt;JoueurArchive&gt;</returns>
        public ApiResponse< List<JoueurArchive> > GetJoueurArchiveCollectionWithHttpInfo (int? page = null)
        {

            var localVarPath = "/joueur_archives";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/html"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (page != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "page", page)); // query parameter

            // authentication (basicAuth) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(Configuration.Username) || !String.IsNullOrEmpty(Configuration.Password))
            {
                localVarHeaderParams["Authorization"] = "Basic " + ApiClient.Base64Encode(Configuration.Username + ":" + Configuration.Password);
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetJoueurArchiveCollection", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<JoueurArchive>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<JoueurArchive>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<JoueurArchive>)));
        }

        /// <summary>
        /// Retrieves the collection of JoueurArchive resources. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">The collection page number (optional)</param>
        /// <returns>Task of List&lt;JoueurArchive&gt;</returns>
        public async System.Threading.Tasks.Task<List<JoueurArchive>> GetJoueurArchiveCollectionAsync (int? page = null)
        {
             ApiResponse<List<JoueurArchive>> localVarResponse = await GetJoueurArchiveCollectionAsyncWithHttpInfo(page);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Retrieves the collection of JoueurArchive resources. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">The collection page number (optional)</param>
        /// <returns>Task of ApiResponse (List&lt;JoueurArchive&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<JoueurArchive>>> GetJoueurArchiveCollectionAsyncWithHttpInfo (int? page = null)
        {

            var localVarPath = "/joueur_archives";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/html"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (page != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "page", page)); // query parameter

            // authentication (basicAuth) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(Configuration.Username) || !String.IsNullOrEmpty(Configuration.Password))
            {
                localVarHeaderParams["Authorization"] = "Basic " + ApiClient.Base64Encode(Configuration.Username + ":" + Configuration.Password);
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetJoueurArchiveCollection", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<JoueurArchive>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<JoueurArchive>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<JoueurArchive>)));
        }

        /// <summary>
        /// Retrieves a JoueurArchive resource. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>JoueurArchive</returns>
        public JoueurArchive GetJoueurArchiveItem (string id)
        {
             ApiResponse<JoueurArchive> localVarResponse = GetJoueurArchiveItemWithHttpInfo(id);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieves a JoueurArchive resource. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of JoueurArchive</returns>
        public ApiResponse< JoueurArchive > GetJoueurArchiveItemWithHttpInfo (string id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling JoueurArchiveApi->GetJoueurArchiveItem");

            var localVarPath = "/joueur_archives/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/html"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", Configuration.ApiClient.ParameterToString(id)); // path parameter

            // authentication (basicAuth) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(Configuration.Username) || !String.IsNullOrEmpty(Configuration.Password))
            {
                localVarHeaderParams["Authorization"] = "Basic " + ApiClient.Base64Encode(Configuration.Username + ":" + Configuration.Password);
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetJoueurArchiveItem", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<JoueurArchive>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (JoueurArchive) Configuration.ApiClient.Deserialize(localVarResponse, typeof(JoueurArchive)));
        }

        /// <summary>
        /// Retrieves a JoueurArchive resource. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>Task of JoueurArchive</returns>
        public async System.Threading.Tasks.Task<JoueurArchive> GetJoueurArchiveItemAsync (string id)
        {
             ApiResponse<JoueurArchive> localVarResponse = await GetJoueurArchiveItemAsyncWithHttpInfo(id);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Retrieves a JoueurArchive resource. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>Task of ApiResponse (JoueurArchive)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<JoueurArchive>> GetJoueurArchiveItemAsyncWithHttpInfo (string id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling JoueurArchiveApi->GetJoueurArchiveItem");

            var localVarPath = "/joueur_archives/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/html"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", Configuration.ApiClient.ParameterToString(id)); // path parameter

            // authentication (basicAuth) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(Configuration.Username) || !String.IsNullOrEmpty(Configuration.Password))
            {
                localVarHeaderParams["Authorization"] = "Basic " + ApiClient.Base64Encode(Configuration.Username + ":" + Configuration.Password);
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetJoueurArchiveItem", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<JoueurArchive>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (JoueurArchive) Configuration.ApiClient.Deserialize(localVarResponse, typeof(JoueurArchive)));
        }

        /// <summary>
        /// Creates a JoueurArchive resource. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="joueurArchive">The new JoueurArchive resource (optional)</param>
        /// <returns>JoueurArchive</returns>
        public JoueurArchive PostJoueurArchiveCollection (JoueurArchive joueurArchive = null)
        {
             ApiResponse<JoueurArchive> localVarResponse = PostJoueurArchiveCollectionWithHttpInfo(joueurArchive);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Creates a JoueurArchive resource. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="joueurArchive">The new JoueurArchive resource (optional)</param>
        /// <returns>ApiResponse of JoueurArchive</returns>
        public ApiResponse< JoueurArchive > PostJoueurArchiveCollectionWithHttpInfo (JoueurArchive joueurArchive = null)
        {

            var localVarPath = "/joueur_archives";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/html"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/html"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (joueurArchive != null && joueurArchive.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(joueurArchive); // http body (model) parameter
            }
            else
            {
                localVarPostBody = joueurArchive; // byte array
            }

            // authentication (basicAuth) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(Configuration.Username) || !String.IsNullOrEmpty(Configuration.Password))
            {
                localVarHeaderParams["Authorization"] = "Basic " + ApiClient.Base64Encode(Configuration.Username + ":" + Configuration.Password);
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PostJoueurArchiveCollection", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<JoueurArchive>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (JoueurArchive) Configuration.ApiClient.Deserialize(localVarResponse, typeof(JoueurArchive)));
        }

        /// <summary>
        /// Creates a JoueurArchive resource. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="joueurArchive">The new JoueurArchive resource (optional)</param>
        /// <returns>Task of JoueurArchive</returns>
        public async System.Threading.Tasks.Task<JoueurArchive> PostJoueurArchiveCollectionAsync (JoueurArchive joueurArchive = null)
        {
             ApiResponse<JoueurArchive> localVarResponse = await PostJoueurArchiveCollectionAsyncWithHttpInfo(joueurArchive);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Creates a JoueurArchive resource. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="joueurArchive">The new JoueurArchive resource (optional)</param>
        /// <returns>Task of ApiResponse (JoueurArchive)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<JoueurArchive>> PostJoueurArchiveCollectionAsyncWithHttpInfo (JoueurArchive joueurArchive = null)
        {

            var localVarPath = "/joueur_archives";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/html"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/html"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (joueurArchive != null && joueurArchive.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(joueurArchive); // http body (model) parameter
            }
            else
            {
                localVarPostBody = joueurArchive; // byte array
            }

            // authentication (basicAuth) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(Configuration.Username) || !String.IsNullOrEmpty(Configuration.Password))
            {
                localVarHeaderParams["Authorization"] = "Basic " + ApiClient.Base64Encode(Configuration.Username + ":" + Configuration.Password);
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PostJoueurArchiveCollection", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<JoueurArchive>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (JoueurArchive) Configuration.ApiClient.Deserialize(localVarResponse, typeof(JoueurArchive)));
        }

        /// <summary>
        /// Replaces the JoueurArchive resource. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="joueurArchive">The updated JoueurArchive resource (optional)</param>
        /// <returns>JoueurArchive</returns>
        public JoueurArchive PutJoueurArchiveItem (string id, JoueurArchive joueurArchive = null)
        {
             ApiResponse<JoueurArchive> localVarResponse = PutJoueurArchiveItemWithHttpInfo(id, joueurArchive);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Replaces the JoueurArchive resource. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="joueurArchive">The updated JoueurArchive resource (optional)</param>
        /// <returns>ApiResponse of JoueurArchive</returns>
        public ApiResponse< JoueurArchive > PutJoueurArchiveItemWithHttpInfo (string id, JoueurArchive joueurArchive = null)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling JoueurArchiveApi->PutJoueurArchiveItem");

            var localVarPath = "/joueur_archives/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/html"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/html"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (joueurArchive != null && joueurArchive.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(joueurArchive); // http body (model) parameter
            }
            else
            {
                localVarPostBody = joueurArchive; // byte array
            }

            // authentication (basicAuth) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(Configuration.Username) || !String.IsNullOrEmpty(Configuration.Password))
            {
                localVarHeaderParams["Authorization"] = "Basic " + ApiClient.Base64Encode(Configuration.Username + ":" + Configuration.Password);
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PutJoueurArchiveItem", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<JoueurArchive>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (JoueurArchive) Configuration.ApiClient.Deserialize(localVarResponse, typeof(JoueurArchive)));
        }

        /// <summary>
        /// Replaces the JoueurArchive resource. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="joueurArchive">The updated JoueurArchive resource (optional)</param>
        /// <returns>Task of JoueurArchive</returns>
        public async System.Threading.Tasks.Task<JoueurArchive> PutJoueurArchiveItemAsync (string id, JoueurArchive joueurArchive = null)
        {
             ApiResponse<JoueurArchive> localVarResponse = await PutJoueurArchiveItemAsyncWithHttpInfo(id, joueurArchive);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Replaces the JoueurArchive resource. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="joueurArchive">The updated JoueurArchive resource (optional)</param>
        /// <returns>Task of ApiResponse (JoueurArchive)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<JoueurArchive>> PutJoueurArchiveItemAsyncWithHttpInfo (string id, JoueurArchive joueurArchive = null)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling JoueurArchiveApi->PutJoueurArchiveItem");

            var localVarPath = "/joueur_archives/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/html"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/html"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (joueurArchive != null && joueurArchive.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(joueurArchive); // http body (model) parameter
            }
            else
            {
                localVarPostBody = joueurArchive; // byte array
            }

            // authentication (basicAuth) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(Configuration.Username) || !String.IsNullOrEmpty(Configuration.Password))
            {
                localVarHeaderParams["Authorization"] = "Basic " + ApiClient.Base64Encode(Configuration.Username + ":" + Configuration.Password);
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PutJoueurArchiveItem", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<JoueurArchive>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (JoueurArchive) Configuration.ApiClient.Deserialize(localVarResponse, typeof(JoueurArchive)));
        }

    }
}
